apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-aws-app-deployment
  labels:
    app: node-aws-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-aws-app
  template:
    metadata:
      labels:
        app: node-aws-app
    spec:
      containers:
      - name: node-aws-app
        image: 510720290862.dkr.ecr.us-east-1.amazonaws.com/node-aws-app:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      imagePullSecrets:
      - name: ecr-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: node-aws-app-service
spec:
  type: NodePort
  selector:
    app: node-aws-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
